# Generated by Django 2.0.4 on 2018-04-16 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gundam_heaven.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField(default=17)),
                ('sex', models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('9', 'Secret')], max_length=10)),
                ('photo', models.ImageField(default='photo/default.jpg', upload_to=gundam_heaven.models.user_dir)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
