# Generated by Django 2.0.4 on 2018-04-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gundam_heaven', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(choices=[('0', 'Female'), ('1', 'Male'), ('9', 'Secret')], default=9),
        ),
    ]
