# Generated by Django 2.0.4 on 2018-04-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gundam_heaven', '0004_article_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gundam_heaven.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('articles', models.ManyToManyField(related_name='tags', through='gundam_heaven.Mark', to='gundam_heaven.Article')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gundam_heaven.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('article', 'tag')},
        ),
    ]
