# Generated by Django 2.0.4 on 2018-04-24 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gundam_heaven', '0010_auto_20180421_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gundam_heaven.Article')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('articles', models.ManyToManyField(through='gundam_heaven.ArticleFollow', to='gundam_heaven.Article')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='articlefollow',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gundam_heaven.FavoriteFolder'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritefolder',
            unique_together={('name', 'owner')},
        ),
    ]
