# Generated by Django 2.0.4 on 2018-04-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gundam_heaven', '0011_auto_20180424_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-update_time',)},
        ),
        migrations.AlterModelOptions(
            name='favoritefolder',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterUniqueTogether(
            name='articlefollow',
            unique_together={('folder', 'article')},
        ),
    ]
